# Generated by Django 5.0.4 on 2024-04-14 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_post_marka_post_brand_post_img_post_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
