# Generated by Django 5.0.4 on 2024-04-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_post_price_alter_post_year_of_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
