# Generated by Django 5.0.4 on 2024-04-14 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_post_year_of_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year_of_issue',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
